Challenge Solved
lamlemonpie/TS-Nederdy-Challanges pull request #1
Opened 2021-06-24 18:33 UTC by lamlemonpie

Temperature Challenge solved

2021-06-28 22:18 UTC, donovanhiland requested changes

2021-06-28 22:18 UTC, donovanhiland commented on src/app.ts
>  }
This is a cool solution! I think it's very readable and gets the job done. Can you tell me about the performance tradeoffs with an approach like this versus doing these calculations in the `processReadings` function?

2021-06-28 22:18 UTC, donovanhiland commented on src/app.ts
> +      average: readings.reduce((a, b) => a + b, 0) / readings.length,
Average should probably be the "average for the day" rather than the average of all days. I'm going to edit the project description to reflect that. Lets make this property here a daily average and add a property to the city with historical lows, highs, and the historical average

2021-06-28 22:31 UTC, lamlemonpie commented on src/app.ts
> +      average: readings.reduce((a, b) => a + b, 0) / readings.length,
I thought of that too, but the tests passed so I assumed it was okay. I will add the properties.

2021-06-28 22:33 UTC, lamlemonpie commented on src/app.ts
>  }
This solution calculates the 5 attributes every time it's requested, so in a situation where many people are requesting this data, a small server could get easily overloaded and if we are going to calculate the same data many times, we should store it instead.

2021-06-29 17:12 UTC, donovanhiland requested changes

2021-06-29 17:12 UTC, donovanhiland commented on src/app.ts
> +    const tmp = reading.temperature
Not completely necessary and definitely a preference thing. But destructuring here might be nice.

```suggestion
    const { city, date, temperature: tmp } = reading
```

2021-06-29 17:12 UTC, donovanhiland commented on src/app.ts
> +    const tmp = reading.temperature
Also technically you don't need to call `toDateString` on the date. If you use it as a key or console log it, it will automatically be a string. You'll get a different result between the browser and node though. It may be safer to use the time since epoch as the key instead? That may be easier to work with than a time stamped string?

```
read.time.getTime()
```

2021-06-29 17:12 UTC, donovanhiland commented on src/app.ts
> +        histLow: +Infinity,
Nice this is a cool solution!

2021-06-29 17:13 UTC, donovanhiland commented on src/app.ts
>  }
Ya definitely. Now what if this code lived on the client? Which approach would you take and why? What are the pros and cons of this approach on the client?

2021-06-29 17:38 UTC, lamlemonpie commented on src/app.ts
>  }
This data is not sensitive, so I don't consider it to be that relevant to keep be kept on the server side. I prefer that these calculations are made on the client side to mitigate the server load and reduce its functions to only store and serve, the downside is the bandwidth used to retrieve the data as it's not summarized.  Also using this approach for transactions like banking or anything with sensitive data is a security leak.
TLTR: it depends on the data, bandwidth and server power.

2021-07-05 16:04 UTC, donovanhiland approved these changes

2021-10-14 23:30 UTC, merged